[project]
name = "pauth"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nic Johnson", email = "nicjohnson145@hotmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "betterproto2==0.9.0",
    "grpcio>=1.78.1",
]

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"
